ROX-6614 Crawl and bundle docker desktop kernels (#129)
Crawl docker desktop install packages from https://docs.docker.com/docker-for-mac/release-notes
and their corresponding kernel sources from https://hub.docker.com/r/docker/for-desktop-kernel.
Use date embedded in kernel banner to distinguish between builds. Kernels do not have a build id, but each kernel release has a different randomization seed.

diff --git a/packers/entrypoint b/packers/entrypoint
--- a/packers/entrypoint
+++ b/packers/entrypoint
@@ -67,6 +67,11 @@ main() {
             repackage_linuxkit "$checksum" "$output_dir" "${packages[@]}"
         ;;
 
+        dockerdesktop)
+            log 'Repackaging Docker Desktop'
+            repackage_dockerdesktop "$checksum" "$output_dir" "${packages[@]}"
+        ;;
+
         oracle)
         	log 'Repackaging oracle'
         	repackage_oracle "$checksum" "$output_dir" "${packages[@]}"
@@ -561,6 +566,94 @@ repackage_linuxkit() {
     )
 }
 
+# Repackages a docker desktop kernel into a bundle tarball.
+repackage_dockerdesktop() {
+    if [[ $# -ne 3 ]]; then
+        log "invalid number of arguments"
+        return 1
+    fi
+
+    local checksum="$1"
+    local output_dir="$2"
+    local input_package_1="$3"
+
+    local kernel_image_dir="$(mktemp -d)"
+    (
+        # The kernel bin image
+        kernel_bin="kernel"
+        # Alpine musl-compiled kernel headers with config and pre-generated random struct seed
+        headers_file="kernel-dev.tar"
+        # Patched kernel sources
+        linux_src_file="linux.tar.xz"
+
+        # Extract input package contents
+        tar -C "$kernel_image_dir" -xzf "$input_package_1" \
+            "$kernel_bin" "$headers_file" "$linux_src_file"
+
+        # Get the compilation date from the kernel binary file, this will be used in the probe name
+        kernel_banner="$(get_kernel_banner "${kernel_image_dir}/${kernel_bin}")"
+        kernel_banner_ts="$(awk -F'SMP ' '{print $2}' <<< "$kernel_banner")"
+        kernel_version_ts="$(date '+%Y-%m-%d-%H-%M-%S' -d "$kernel_banner_ts")"
+
+        # Extract and find the name of the kernel directory which contains the config file
+        headers_root="$(mktemp -d)"
+        tar -C "${headers_root}" -xf "${kernel_image_dir}/kernel-dev.tar"
+        headers_base="$(basename "$(find "${headers_root}" -type d -name 'linux-headers-*-linuxkit')")"
+        echo "Headers base is ${headers_base}"
+        headers_dir="${headers_root}/usr/src/${headers_base}"
+
+        # Extract the kernel source directory will be used as the root of the resulting archive
+        linux_src_root="$(mktemp -d)"
+        tar -C "${linux_src_root}" -xf "${kernel_image_dir}/linux.tar.xz"
+        cd "${linux_src_root}/linux"
+        linux_src_dir="${linux_src_root}/linux"
+
+        # Copy kernel config
+        cp "${headers_dir}/.config" "${linux_src_dir}/"
+
+        # Copy pre-generated seed and seed hash used for struct randomization
+        rand_seed_file="scripts/gcc-plugins/randomize_layout_seed.h"
+        rand_seed_hash_file="include/generated/randomize_layout_hash.h"
+        cp "${headers_dir}/${rand_seed_file}" "${linux_src_dir}/${rand_seed_file}"
+        mkdir -p "$(dirname ${rand_seed_hash_file})"
+        cp "${headers_dir}/${rand_seed_hash_file}" "${linux_src_dir}/${rand_seed_hash_file}"
+
+        # Get kernel version from Makefile
+        cd "${linux_src_dir}"
+        local kernel_make_version="$(cat Makefile | grep '^VERSION ='    | head -n1 | cut -d ' ' -f 3)"
+        local kernel_make_major="$(cat   Makefile | grep '^PATCHLEVEL =' | head -n1 | cut -d ' ' -f 3)"
+        local kernel_make_minor="$(cat   Makefile | grep '^SUBLEVEL ='   | head -n1 | cut -d ' ' -f 3)"
+        local kernel_version="${kernel_make_version}.${kernel_make_major}.${kernel_make_minor}"
+        local kernel_uname="${kernel_version}-linuxkit"
+
+        # Custom name used to identify this kernel and random seed by date
+        local probe_name="${kernel_version}-dockerdesktop-${kernel_version_ts}"
+
+        # sanity check
+        [[ "${headers_base#"linux-headers-"}" == "${kernel_uname}" ]] || exit 1
+
+        log "Kernel banner is \"${kernel_banner}\""
+        log "Probe name is ${probe_name}"
+        log "Kernel uname is ${kernel_uname}"
+
+        # Generate bundle meta files
+        meta_dir="$(bundle_meta "$checksum" 'dockerdesktop' "$kernel_uname" '.')"
+
+        # Prepare kernel sources for module compilation
+        make olddefconfig > /dev/null
+        make modules_prepare > /dev/null
+
+        # Delete all *.c files, excluding scripts directory
+        find "${linux_src_dir}" ! \( -type d \) -not -path "${linux_src_dir}/scripts/*" -name "*.c" -delete
+
+        # Compress only part of the file hierarchy into a tarball.
+        tar --create --dereference --hard-dereference --file - \
+            --directory "$meta_dir" . \
+            --directory "${linux_src_dir}" . \
+        | pigz -9 -c > "${output_dir}/bundle-${probe_name}.tgz"
+    )
+}
+
 # Repackages a kernel into a bundle tarball.
 repackage_oracle() {
     if [[ $# -ne 3 ]]; then
@@ -633,6 +726,15 @@ bundle_meta() {
     echo -n "$build_dir"      > "${tmp_dir}/BUNDLE_BUILD_DIR"
 
     echo "$tmp_dir"
+}
+
+get_kernel_banner() {
+    kernel_bin="$1"
+    [[ -n "${kernel_bin}" ]] || ( log "empty kernel bin parameter" && exit 1 )
+    # Find location of the gzip magic number header (similar to linux/scripts/extract-vmlinux)
+    skip="$(LC_ALL=C grep -a -b -o $'\x1f\x8b\x08\x00\x00\x00\x00\x00' "${kernel_bin}" | head -n 1 | cut -d ':' -f 1)"
+    # Skip to start of compressed kernel region and extract uname banner
+    dd if="${kernel_bin}" bs=1 skip="$skip" | zcat -q | tr -d '\0' | grep -a 'Linux version [0-9]' || true
 }
 
 log() {
