X-Smart-Squash: Squashed 19 commits:
2585b88 Fixes for docker desktop kernels
8cb6b6f PR staging info comment
1de1185 newer ubuntu packages use zstd compresion, unsupported by debian dpkg
973ca28 Trigger build all
1e45b5b gcc-8-plugin
72c77f7 chmod
35bb731 path
307b0e5 staging
c0924e5 typo
3aecd6e comment details
3e30abb update template
215e243 varname
1fd2c50 update
2b41c23 typo
483c8d94 fix local var
99b6c04b rm no-op
d92f19a8 restore HOSTCC setting:
6562d094 revert again
0fb893e7 formatting

diff --git a/packers/entrypoint b/packers/entrypoint
--- a/packers/entrypoint
+++ b/packers/entrypoint
@@ -433,8 +433,8 @@ repackage_ubuntu() {
         cd "$tmp_dir"
 
         # Extract the DEB packages.
-        dpkg -x "$input_package_1" .
-        dpkg -x "$input_package_2" .
+        extract_deb "$input_package_1" "${tmp_dir}"
+        extract_deb "$input_package_2" "${tmp_dir}"
 
         # Find the name of the kernel directory.
         # Variable will contain a string that should looks like "4.15.0-1023-aws".
@@ -631,11 +631,11 @@ repackage_dockerdesktop() {
 
         # If present, copy pre-generated seed and seed hash used for struct randomization
         rand_seed_file="scripts/gcc-plugins/randomize_layout_seed.h"
-        if [[ -f "${rand_seed_file}" ]]; then
+        if [[ -f "${headers_dir}/${rand_seed_file}" ]]; then
             cp "${headers_dir}/${rand_seed_file}" "${linux_src_dir}/${rand_seed_file}"
         fi
         rand_seed_hash_file="include/generated/randomize_layout_hash.h"
-        if [[ -f "${rand_seed_hash_file}" ]]; then
+        if [[ -f "${headers_dir}/${rand_seed_hash_file}" ]]; then
             mkdir -p "$(dirname ${rand_seed_hash_file})"
             cp "${headers_dir}/${rand_seed_hash_file}" "${linux_src_dir}/${rand_seed_hash_file}"
         fi
@@ -751,12 +751,31 @@ bundle_meta() {
 }
 
 get_kernel_banner() {
-    kernel_bin="$1"
+    local kernel_bin="$1"
     [[ -n "${kernel_bin}" ]] || ( log "empty kernel bin parameter" && exit 1 )
     # Find location of the gzip magic number header (similar to linux/scripts/extract-vmlinux)
     skip="$(LC_ALL=C grep -a -b -o $'\x1f\x8b\x08\x00\x00\x00\x00\x00' "${kernel_bin}" | head -n 1 | cut -d ':' -f 1)"
     # Skip to start of compressed kernel region and extract uname banner
     dd if="${kernel_bin}" bs=1 skip="$skip" | zcat -q | tr -d '\0' | grep -a 'Linux version [0-9]' || true
+}
+
+extract_deb() {
+    local deb_file="$1"
+    local output_dir="$2"
+    # Try to extract the deb file using dpkg, if that fails, attempt to extract with ar/zstd/tar.
+    if ! dpkg -x "${deb_file}" "${output_dir}" ; then
+        log "Trying manual zstd extract of ${deb_file}"
+        zstd_file="data.tar.zst"
+        mkdir -p "${output_dir}"
+        pushd "${output_dir}" > /dev/null
+        ar -x "${deb_file}" "${zstd_file}"
+        popd > /dev/null
+        if [[ ! -f "${output_dir}/${zstd_file}" ]] ; then
+            return 1
+        fi
+        zstd -dcfq "${output_dir}/${zstd_file}" | tar xf - -C "${output_dir}"
+    fi
+    return 0
 }
 
 log() {
