Split crawl status check

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -298,11 +298,21 @@ jobs:
           [[ "$CIRCLE_BRANCH" =~ ^(master|main)$ ]] || exit 0
           make robo-crawl-commit
 
+    - persist_to_workspace:
+        root: /tmp
+        paths:
+          - crawl-failed
+  crawl-status:
+    <<: *defaults
+    steps:
+    - attach_workspace:
+        at: /tmp
+
     - run:
         name: Test if crawling failed
         command: |
           if [[ -f /tmp/crawl-failed ]] || grep -Eq '\*\*\* \[[a-zA-Z0-9-]+\] Error' /tmp/make-crawl-stderr ; then
-            echo "'make crawl' failed. See the output of the 'Crawl package repositories' step for further details."
+            echo >&2 "'make crawl' failed. See the output of the 'Crawl package repositories' step in the crawl job for further details."
             exit 1
           fi
 
@@ -338,6 +348,9 @@ workflows:
         <<: *crawlContext
         requires:
         - lint
+    - crawl-status:
+        requires:
+        - crawl-build
     - repackage:
         requires:
         - crawl-build
