update

diff --git a/scripts/local-bundle b/scripts/local-bundle
--- a/scripts/local-bundle
+++ b/scripts/local-bundle
@@ -1,14 +1,41 @@
 #! /bin/bash
 
+# Create a manifest file that only contains kernel versions matching the given regex
+# e.g., "./scripts/local-bundle 3.10.0-1127" or "./scripts/local-bundle .*el7.*"
+
+# Steps
 # 1. check that we have jq and yq
 # 2. check that filter query exists in existing manifest
 # 3. create tempoary manifest and build
 
 DIR="$(cd "$(dirname "$0")" && pwd)"
-set -e
+
+set -eo pipefail
+
+die() {
+    echo >&2 "$@"
+    exit 1
+}
+
+function toolcheck {
+  if ! command -v "$1" &> /dev/null ; then
+    die "Error: The $1 utility could not be found, install with 'brew install $1'"
+  fi
+}
+
+KERNEL_REGEX="$1"
+
+[[ -n "$KERNEL_REGEX" ]] \
+    || die "Usage: $0 <kernel-version-regex>"
+
+toolcheck jq
+toolcheck iq
+toolcheck yq
 
 tmp_manifest="$(mktemp)"
-yq r -j "${DIR}/../kernel-package-lists/manifest.yml" | jq 'to_entries[] | select(.value.packages[] | contains("'"$1"'")) | [.] | from_entries' | jq -s add | yq r -P - > "${tmp_manifest}"
+yq r -j "${DIR}/../kernel-package-lists/manifest.yml" | \
+  jq 'to_entries[] | select(.value.packages[] | test("'"$KERNEL_REGEX"'")) | [.] | from_entries' | \
+  jq -s add | yq r -P - > "${tmp_manifest}"
 
 echo "Filtered manifest ${tmp_manifest}"
 cat "${tmp_manifest}"
