Some further fixes following PR review

diff --git a/.github/workflows/crawl.yml b/.github/workflows/crawl.yml
--- a/.github/workflows/crawl.yml
+++ b/.github/workflows/crawl.yml
@@ -34,7 +34,7 @@ jobs:
           fi
 
           if [[ -f /tmp/crawl-failed ]] || grep -Eq '\*\*\* \[[a-zA-Z0-9-]+\] Error' /tmp/make-crawl-stderr ; then
-              echo >&2 "'make crawl' failed. See the output of the 'Crawl package repositories' step in the crawl job for further details."
+              echo >&2 "'make crawl' failed."
               exit 1
           fi
 
@@ -73,6 +73,7 @@ jobs:
         with:
           name: kernel-crawler-manifest
           path: kernel-package-lists/manifest.yml
+          retention-days: 1
 
       - name: Archive log files
         if: always()
@@ -80,6 +81,7 @@ jobs:
         with:
           name: kernel-crawler-logs
           if-no-files-found: ignore
+          retention-days: 3
           path: |
             all-crawled-packages.log
             all-bucket-files.log
