Delay errors so repackaging can take place

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -15,3 +15,32 @@ jobs:
     needs: crawl
     secrets: inherit
 
+  check-errors:
+    needs: crawl
+    runs-on: ubuntu-latest
+    steps:
+    - name: Restore files
+      uses: actions/download-artifact@v3
+      with:
+        name: kernel-crawler-errors
+        path: /tmp/
+
+    - name: Check errors
+      run: |
+        if [[ -f /tmp/crawl-failed ]] || grep -Eq '\*\*\* \[[a-zA-Z0-9-]+\] Error' /tmp/make-crawl-stderr ; then
+            echo >&2 "'make crawl' failed."
+            exit 1
+        fi
+
+    - name: Slack notification
+      if: failure() && github.event_name == 'schedule'
+      uses: rtCamp/action-slack-notify@v2
+      env:
+        SLACK_WEBHOOK: ${{ secrets.SLACK_COLLECTOR_ONCALL_WEBHOOK }}
+        SLACK_CHANNEL: team-acs-collector-oncall
+        SLACK_COLOR: ${{ job.status }}
+        SLACK_LINK_NAMES: true
+        SLACK_TITLE: Kernel Crawling Failed
+        MSG_MINIMAL: actions url,commit
+        SLACK_MESSAGE: |
+          @acs-collector-team
